import { getRandomIndex } from './getRandomIndex';
export const loremGenerator = () => {
   const lorems = [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ornare cursus lorem, non mollis risus. Suspendisse mattis diam quis rhoncus rhoncus. Phasellus dapibus tincidunt orci eu ornare. Phasellus tempor nisl et dolor lobortis, nec tempor risus finibus. Nam eros augue, pulvinar id dictum vulputate, ornare in mauris. Aliquam id lacus tempor, iaculis diam non, aliquam justo. Nullam accumsan euismod ipsum, sed laoreet dui lacinia non.',
      'Donec dignissim magna nec dolor mollis egestas eu at odio. Fusce maximus purus et quam pellentesque, quis tristique leo vestibulum. Vestibulum sapien ante, facilisis vel tortor pretium, mollis finibus erat. Etiam ut augue quam. Proin accumsan, nunc a euismod commodo, dolor lorem ultricies est, a cursus nulla odio interdum elit.',
      'Nunc eget ultricies lectus, vitae sollicitudin arcu. Sed dignissim risus a lorem tempor convallis. Nulla euismod, metus nec euismod vestibulum, arcu lectus feugiat magna, vel pulvinar ex turpis sit amet ipsum. Ut non lorem consequat, sollicitudin libero et, facilisis mi. Proin auctor porttitor metus, at tincidunt eros dictum facilisis. Ut rhoncus turpis a tellus porta laoreet. Sed gravida malesuada eros. Sed varius orci in arcu dapibus tempor.',
      'Sed eu aliquam sapien. Donec ligula lectus, rhoncus quis placerat vel, consectetur sed erat. In hac habitasse platea dictumst. Maecenas quis lectus fermentum, venenatis justo in, congue enim. Nullam mi eros, convallis vitae imperdiet at, interdum nec est. Quisque tempus ex ac lacus pharetra, non efficitur diam commodo. Nunc in erat vitae tellus mollis vulputate vitae quis mauris. Sed eu urna nisl.',
      'Phasellus lacinia laoreet libero, a iaculis mi vestibulum et. Nulla gravida, odio in placerat ultricies, mauris arcu sagittis augue, ut rutrum lacus dolor sit amet odio. Duis vitae ipsum velit. Etiam odio nulla, sollicitudin a convallis at, fermentum sed purus. Fusce blandit ante et lectus fermentum, in laoreet orci sodales. Nam placerat justo neque, ac molestie arcu luctus auctor.',
      'Uspendisse ut mi mattis, efficitur lorem eget, porta massa. Praesent mi dolor, posuere sit amet mauris eu, laoreet volutpat mi. Maecenas nec odio arcu. Vestibulum cursus lacus ullamcorper mattis cursus. Praesent efficitur tincidunt ultrices. Vivamus pretium sapien nec tortor ultricies, nec vehicula turpis lobortis. Praesent lorem mauris, sagittis vel luctus nec, blandit eu odio.',
      'Nam ultricies suscipit magna, vitae dapibus ante blandit ut. Suspendisse vel iaculis odio. Pellentesque tincidunt leo dignissim, eleifend ex ultricies, pharetra ex. In finibus felis nisi. Duis maximus sem dui, sed sollicitudin lorem mattis ut. Aenean eu ligula arcu. Pellentesque facilisis laoreet ex at vestibulum. Etiam ex enim, laoreet id nunc vitae, fermentum lacinia lorem.',
   ];

   return lorems[getRandomIndex(lorems.length)];
};
